import { describe, it, expect } from 'vitest';
import { generateTypeFile } from '../src/codegen/type-generator';
import { generateQueryFile } from '../src/codegen/query-generator';
import { parseSQL } from '../src/codegen/sql-parser';
import { buildBarrelContent } from '../src/codegen/generate';
import { safeIdentifier, isReservedWord } from '../src/codegen/utils';
import type { TableSchema } from '../src/codegen/glue-fetcher';

describe('generateTypeFile', () => {
  it('generates interface from table schema', () => {
    const schema: TableSchema = {
      database: 'sampledb',
      tableName: 'events',
      columns: [
        { name: 'event_id', type: 'integer', nullable: false },
        { name: 'event_name', type: 'varchar', nullable: true },
        { name: 'is_active', type: 'boolean', nullable: false },
        { name: 'price', type: 'decimal(10,2)', nullable: true },
        { name: 'created_at', type: 'timestamp', nullable: true },
        { name: 'tags', type: 'array<varchar>', nullable: true },
      ],
    };

    const output = generateTypeFile(schema);

    expect(output).toContain('export interface Events {');
    expect(output).toContain('event_id: number;');
    expect(output).toContain('event_name: string | null;');
    expect(output).toContain('is_active: boolean;');
    expect(output).toContain('price: string | null;');
    expect(output).toContain('created_at: Date | null;');
    expect(output).toContain('tags: string[] | null;');
    expect(output).toContain('Source: sampledb.events');
    expect(output).toContain('Auto-generated by aathena');
  });
});

describe('generateTypeFile indent option', () => {
  it('honours a custom indent string', () => {
    const schema: TableSchema = {
      database: 'sampledb',
      tableName: 'events',
      columns: [{ name: 'event_id', type: 'integer', nullable: false }],
    };

    const output = generateTypeFile(schema, '    ');

    expect(output).toContain('    event_id: number;');
    expect(output).toMatch(/^ {4}event_id: number;$/m);
  });
});

describe('generateQueryFile', () => {
  it('generates query file with inferred params', () => {
    const sql = `SELECT * FROM events WHERE status = '{{status}}' LIMIT {{rowLimit}}`;
    const parsed = parseSQL(sql);

    const output = generateQueryFile({
      sqlRelativePath: 'tables/sampledb/events/product.sql',
      tableName: 'events',
      database: 'sampledb',
      primaryDatabase: 'sampledb',
      parsed,
      typesImportPath: '../../types/sampledb/events',
    });

    expect(output).toContain("from 'aathena/runtime'");
    expect(output).toContain("import type { Events } from '../../types/sampledb/events'");
    expect(output).toContain('export interface ProductParams {');
    expect(output).toContain('status: string;');
    expect(output).toContain('rowLimit: number;');
    expect(output).toContain('export const product = createQuery');
    expect(output).toContain('tables/sampledb/events/product.sql');
    expect(output).not.toContain('database:');
  });

  it('generates query file with @param annotations and schema', () => {
    const sql = `-- @param status enum('active','pending')
-- @param rowLimit positiveInt
SELECT * FROM events WHERE status = '{{status}}' LIMIT {{rowLimit}}`;
    const parsed = parseSQL(sql);

    const output = generateQueryFile({
      sqlRelativePath: 'tables/sampledb/events/product.sql',
      tableName: 'events',
      database: 'sampledb',
      primaryDatabase: 'sampledb',
      parsed,
      typesImportPath: '../../types/sampledb/events',
    });

    expect(output).toContain("status: 'active' | 'pending';");
    expect(output).toContain("schema.enum('active', 'pending')");
    expect(output).toContain('schema.positiveInt');
    expect(output).toContain('schemaDef');
  });

  it('generates query file without params', () => {
    const sql = `SELECT COUNT(*) as cnt FROM events`;
    const parsed = parseSQL(sql);

    const output = generateQueryFile({
      sqlRelativePath: 'tables/sampledb/events/count.sql',
      tableName: 'events',
      database: 'sampledb',
      primaryDatabase: 'sampledb',
      parsed,
      typesImportPath: '../../types/sampledb/events',
    });

    expect(output).toContain('Record<string, never>');
    expect(output).not.toContain('Params');
  });

  it('binds per-query database when directory differs from primary (no params)', () => {
    const sql = `SELECT COUNT(*) as cnt FROM events`;
    const parsed = parseSQL(sql);

    const output = generateQueryFile({
      sqlRelativePath: 'tables/sales/events/count.sql',
      tableName: 'events',
      database: 'sales',
      primaryDatabase: 'marketing',
      parsed,
      typesImportPath: '../../types/sales/events',
    });

    expect(output).toContain(`{ database: 'sales' }`);
    expect(output).toContain('undefined,');
  });

  it('binds per-query database when directory differs (with params, no schema)', () => {
    const sql = `SELECT * FROM events WHERE status = '{{status}}' AND name = '{{name}}'`;
    const parsed = parseSQL(sql);

    const output = generateQueryFile({
      sqlRelativePath: 'tables/sales/events/product.sql',
      tableName: 'events',
      database: 'sales',
      primaryDatabase: 'marketing',
      parsed,
      typesImportPath: '../../types/sales/events',
    });

    expect(output).toContain(`{ database: 'sales' }`);
    expect(output).toContain('undefined,');
    expect(output).not.toContain('schemaDef');
  });

  it('binds per-query database with @param schema', () => {
    const sql = `-- @param status enum('active','pending')
SELECT * FROM events WHERE status = '{{status}}'`;
    const parsed = parseSQL(sql);

    const output = generateQueryFile({
      sqlRelativePath: 'tables/sales/events/product.sql',
      tableName: 'events',
      database: 'sales',
      primaryDatabase: 'marketing',
      parsed,
      typesImportPath: '../../types/sales/events',
    });

    expect(output).toContain('schemaDef');
    expect(output).toContain(`{ database: 'sales' }`);
    expect(output).not.toContain('undefined,');
  });
});

describe('generateQueryFile indent option', () => {
  it('applies a custom indent to params, schemaDef, and createQuery args', () => {
    const sql = `-- @param status enum('active','pending')
SELECT * FROM events WHERE status = '{{status}}'`;
    const parsed = parseSQL(sql);

    const output = generateQueryFile({
      sqlRelativePath: 'tables/sampledb/events/product.sql',
      tableName: 'events',
      database: 'sampledb',
      primaryDatabase: 'sampledb',
      parsed,
      typesImportPath: '../../types/sampledb/events',
      indent: '    ',
    });

    expect(output).toContain("    status: 'active' | 'pending';");
    expect(output).toContain("    status: schema.enum('active', 'pending'),");
    expect(output).toContain("    'tables/sampledb/events/product.sql',");
    expect(output).toContain('    schemaDef,');
  });

  it('applies custom indent to per-query database binding', () => {
    const sql = `SELECT COUNT(*) AS cnt FROM events`;
    const parsed = parseSQL(sql);

    const output = generateQueryFile({
      sqlRelativePath: 'tables/sales/events/count.sql',
      tableName: 'events',
      database: 'sales',
      primaryDatabase: 'marketing',
      parsed,
      typesImportPath: '../../types/sales/events',
      indent: '\t',
    });

    expect(output).toContain("\t{ database: 'sales' },");
    expect(output).toContain('\tundefined,');
  });
});

describe('safeIdentifier / isReservedWord', () => {
  it('flags JS keywords as reserved', () => {
    expect(isReservedWord('default')).toBe(true);
    expect(isReservedWord('class')).toBe(true);
    expect(isReservedWord('return')).toBe(true);
    expect(isReservedWord('await')).toBe(true);
    expect(isReservedWord('yield')).toBe(true);
  });

  it('passes non-reserved names through', () => {
    expect(isReservedWord('events')).toBe(false);
    expect(isReservedWord('product')).toBe(false);
    expect(safeIdentifier('events')).toBe('events');
    expect(safeIdentifier('latest')).toBe('latest');
  });

  it('suffixes reserved words with _', () => {
    expect(safeIdentifier('default')).toBe('default_');
    expect(safeIdentifier('class')).toBe('class_');
  });
});

describe('generateQueryFile reserved-word handling', () => {
  it('emits a safe identifier for a default.sql file', () => {
    const sql = `SELECT COUNT(*) AS cnt FROM events`;
    const parsed = parseSQL(sql);

    const output = generateQueryFile({
      sqlRelativePath: 'tables/sampledb/events/default.sql',
      tableName: 'events',
      database: 'sampledb',
      primaryDatabase: 'sampledb',
      parsed,
      typesImportPath: '../../types/sampledb/events',
    });

    expect(output).toContain('export const default_ = createQuery');
    expect(output).not.toMatch(/export const default = /);
  });
});

describe('buildBarrelContent', () => {
  const schemas = new Map([
    ['sampledb.events', { database: 'sampledb', tableName: 'events', columns: [] }],
  ]);

  it('aliases a reserved-word query even when it is the only one', () => {
    const out = buildBarrelContent(
      [
        {
          database: 'sampledb',
          tableName: 'events',
          queryName: 'default',
          relativeDirFromTables: 'sampledb/events',
        },
      ],
      schemas,
    );
    expect(out).toContain(
      `export { default_ as eventsDefault } from './queries/sampledb/events/default';`,
    );
  });

  it('exports a plain name when not reserved and not duplicated', () => {
    const out = buildBarrelContent(
      [
        {
          database: 'sampledb',
          tableName: 'events',
          queryName: 'latest',
          relativeDirFromTables: 'sampledb/events',
        },
      ],
      schemas,
    );
    expect(out).toContain(
      `export { latest } from './queries/sampledb/events/latest';`,
    );
  });

  it('aliases duplicates across tables with {table}{Query}', () => {
    const twoTableSchemas = new Map([
      ['sampledb.events', { database: 'sampledb', tableName: 'events', columns: [] }],
      ['sampledb.users', { database: 'sampledb', tableName: 'users', columns: [] }],
    ]);
    const out = buildBarrelContent(
      [
        {
          database: 'sampledb',
          tableName: 'events',
          queryName: 'latest',
          relativeDirFromTables: 'sampledb/events',
        },
        {
          database: 'sampledb',
          tableName: 'users',
          queryName: 'latest',
          relativeDirFromTables: 'sampledb/users',
        },
      ],
      twoTableSchemas,
    );
    expect(out).toContain(
      `export { latest as eventsLatest } from './queries/sampledb/events/latest';`,
    );
    expect(out).toContain(
      `export { latest as usersLatest } from './queries/sampledb/users/latest';`,
    );
  });
});
