import type { ParsedParam, ParsedSQL } from './sql-parser';
import { pascalCase, camelCase } from './utils';

const HEADER = '// Auto-generated by aathena\n';

export interface QueryGenInput {
  /** Relative path from project root to the SQL file, e.g. "tables/sampledb/events/product.sql" */
  sqlRelativePath: string;
  /** Table name extracted from directory structure */
  tableName: string;
  /** Database name extracted from directory structure */
  database: string;
  /** Parsed SQL with extracted params */
  parsed: ParsedSQL;
  /** Relative import path from generated query file to types file */
  typesImportPath: string;
}

export function generateQueryFile(input: QueryGenInput): string {
  const interfaceName = pascalCase(input.tableName);
  const queryFnName = camelCase(fileNameWithoutExt(input.sqlRelativePath));
  const params = input.parsed.params;

  const hasSchema = params.length > 0 && params.some((p) => p.schemaType);
  const runtimeImports = hasSchema ? 'createQuery, schema' : 'createQuery';

  const lines: string[] = [
    HEADER,
    `// Source: ${input.sqlRelativePath}`,
    '',
    `import { ${runtimeImports} } from 'aathena/runtime';`,
    `import type { ${interfaceName} } from '${input.typesImportPath}';`,
  ];

  // Generate params interface if there are params
  if (params.length > 0) {
    const paramsInterfaceName = `${pascalCase(queryFnName)}Params`;
    lines.push('');
    lines.push(`export interface ${paramsInterfaceName} {`);
    for (const p of params) {
      lines.push(`  ${p.name}: ${p.type};`);
    }
    lines.push('}');
    lines.push('');

    // Generate schema definition if any params have schema types
    if (hasSchema) {
      lines.push(`const schemaDef = {`);
      for (const p of params) {
        lines.push(`  ${p.name}: ${schemaExpression(p)},`);
      }
      lines.push('};');
      lines.push('');
      lines.push(
        `export const ${queryFnName} = createQuery<${interfaceName}, ${paramsInterfaceName}>(`,
      );
      lines.push(`  '${input.sqlRelativePath}',`);
      lines.push(`  schemaDef,`);
      lines.push(`);`);
    } else {
      lines.push(
        `export const ${queryFnName} = createQuery<${interfaceName}, ${paramsInterfaceName}>(`,
      );
      lines.push(`  '${input.sqlRelativePath}',`);
      lines.push(`);`);
    }
  } else {
    // No params - simple query
    lines.push('');
    lines.push(
      `export const ${queryFnName} = createQuery<${interfaceName}, Record<string, never>>(`,
    );
    lines.push(`  '${input.sqlRelativePath}',`);
    lines.push(`);`);
  }

  lines.push('');
  return lines.join('\n');
}

function schemaExpression(param: ParsedParam): string {
  if (!param.schemaType) {
    if (param.type === 'number') return 'schema.number';
    if (param.type === 'boolean') return 'schema.boolean';
    return 'schema.string';
  }

  switch (param.schemaType) {
    case 'enum':
      return `schema.enum(${(param.enumValues ?? []).map((v) => `'${v}'`).join(', ')})`;
    case 'positiveInt':
      return 'schema.positiveInt';
    case 'isoDate':
      return 'schema.isoDate';
    case 'isoTimestamp':
      return 'schema.isoTimestamp';
    case 'identifier':
      return 'schema.identifier';
    case 'uuid':
      return 'schema.uuid';
    case 's3Path':
      return 'schema.s3Path';
    case 'number':
      return 'schema.number';
    case 'boolean':
      return 'schema.boolean';
    case 'string':
      return 'schema.string';
    default:
      return 'schema.string';
  }
}

function fileNameWithoutExt(filePath: string): string {
  const parts = filePath.split('/');
  const fileName = parts[parts.length - 1];
  return fileName.replace(/\.\w+$/, '');
}
