import type { TableSchema } from './glue-fetcher';
import { athenaTypeToTS } from './type-map';
import { pascalCase } from './utils';

const HEADER = '// Auto-generated by aathena\n';

export function generateTypeFile(schema: TableSchema, indent = '  '): string {
  const interfaceName = pascalCase(schema.tableName);

  const lines: string[] = [
    HEADER,
    `// Source: ${schema.database}.${schema.tableName}`,
    '',
    `export interface ${interfaceName} {`,
  ];

  for (const col of schema.columns) {
    const tsType = athenaTypeToTS(col.type);
    const fullType = col.nullable ? `${tsType} | null` : tsType;
    const comment = col.comment ? ` // ${col.comment}` : typeComment(col.type);
    lines.push(`${indent}${col.name}: ${fullType};${comment}`);
  }

  lines.push('}', '');

  return lines.join('\n');
}

function typeComment(athenaType: string): string {
  const t = athenaType.toLowerCase();
  // Add comments for non-obvious mappings
  if (t.startsWith('decimal')) return ' // decimal → string (precision safe)';
  if (t === 'date') return ' // YYYY-MM-DD';
  if (t.startsWith('array')) return ` // ${athenaType}`;
  if (t.startsWith('map')) return ` // ${athenaType}`;
  if (t.startsWith('struct')) return ` // ${athenaType}`;
  if (t === 'bigint') return ' // JS BigInt';
  return '';
}

