import type { TableSchema } from './glue-fetcher';
import { athenaTypeToTS } from './type-map';

const HEADER = '// Auto-generated by aathena, do not edit\n';

export function generateTypeFile(schema: TableSchema): string {
  const interfaceName = pascalCase(schema.tableName);

  const lines: string[] = [
    HEADER,
    `// Source: ${schema.database}.${schema.tableName}`,
    '',
    `export interface ${interfaceName} {`,
  ];

  for (const col of schema.columns) {
    const tsType = athenaTypeToTS(col.type);
    const comment = col.comment ? ` // ${col.comment}` : typeComment(col.type, tsType);
    lines.push(`  ${col.name}: ${tsType};${comment}`);
  }

  lines.push('}', '');

  return lines.join('\n');
}

function typeComment(athenaType: string, _tsType: string): string {
  const t = athenaType.toLowerCase();
  // Add comments for non-obvious mappings
  if (t.startsWith('decimal')) return ' // decimal → string (precision safe)';
  if (t === 'date') return ' // YYYY-MM-DD';
  if (t.startsWith('array')) return ` // ${athenaType}`;
  if (t.startsWith('map')) return ` // ${athenaType}`;
  if (t.startsWith('struct')) return ` // ${athenaType}`;
  if (t === 'bigint') return ' // bigint → number';
  return '';
}

function pascalCase(str: string): string {
  return str
    .split(/[_\-\s]+/)
    .map((s) => s.charAt(0).toUpperCase() + s.slice(1).toLowerCase())
    .join('');
}
